name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile src/main.py --clean
          mkdir -p release
          cp dist/main release/musicdownloadbot
          chmod +x release/musicdownloadbot

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/musicdownloadbot
            installer.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
